version: '3.3'

services:
    back:
        build: .
        container_name: steppy-back
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
        networks:
            - steppy

    db:
        image: postgres
        container_name: steppy-back-db
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=Admin2776!
            - POSTGRES_USER=admin
            - POSTGRES_DB=steppy
        ports:
            - "5432:5432"
        volumes:
            - ./docker-compose/postgres:/var/lib/postgresql/data
        networks:
            - steppy

networks:
    steppy:
        driver: bridge
